// filename: src/components/ProcessingScreen.jsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useEffect, useMemo, useState } from 'react';

function guessTargetSheetName(row) {
  const sheet = (row.sheetName || '').toLowerCase();
  const label = (row.fileLabel || '').toLowerCase();
  if (label.includes('net trust')) return '2. Summary of Net Trust Asset';
  if (sheet.includes('loan')) return '4. Loan';
  return '3. Summary of Plan Ops';
}

function parseLines(text) {
  return text.split('\n').map(line => line.trim()).filter(Boolean);
}

function parseCombineGroups(text) {
  const result = {};
  for (const line of parseLines(text)) {
    const [outName, rest] = line.split(':');
    if (!outName || !rest) continue;
    result[outName.trim()] = rest.split(',').map(s => s.trim()).filter(Boolean);
  }
  return result;
}

function colLetterToIndex(letter) {
  return letter.toUpperCase().split('').reduce((acc, ch) => acc * 26 + ch.charCodeAt(0) - 64, 0) - 1;
}

function resolveDisplayHeader(c) {
  if (!c) return '';
  return c.actualHeader || c.expectedHeader || `col_${c.column}`;
}

function resolvePayloadHeader(c) {
  if (!c) return '';
  if (c.actualHeader || c.expectedHeader) return c.actualHeader || c.expectedHeader;
  return `Unnamed: ${colLetterToIndex(c.column)}`;
}

function sanitizeSheetName(value, fallback = 'Summary') {
  const cleaned = String(value || '')
    .replace(/[\\/*?:[\]]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return (cleaned || fallback).slice(0, 31);
}

function defaultSummarySheetName(row, index) {
  const seed = row.sheetName || row.fileLabel || row.fileName || `Summary ${index + 1}`;
  return sanitizeSheetName(`${seed} Summary`, `Summary ${index + 1}`);
}

function inputStyle(width = '100%') {
  return {
    width,
    padding: '9px 11px',
    borderRadius: 7,
    border: '1px solid var(--border)',
    background: 'var(--bg)',
    color: 'var(--fg)',
    fontSize: 13
  };
}

function Field({ label, children }) {
  return (
    <label style={{ display: 'flex', flexDirection: 'column', gap: 6, fontSize: 12, color: 'var(--fg-muted)' }}>
      <span style={{ fontWeight: 600, letterSpacing: 0.2 }}>{label}</span>
      {children}
    </label>
  );
}

const DEFAULT_GROUP_HEADERS = [
  'Contributions/Employer',
  'Contributions/Employee',
  'Adjustment (+)',
  'Adjustment (-)',
  'Administrative Fee',
  'Realized Gain/(Loss)',
  'Unrealized Gain/(Loss)',
  'Interest and Dividends',
  'Benefit Payments'
];

const DEFAULT_SECTION_GROUPS = ['Contributions/Employer', 'Contributions/Employee'];
const DEFAULT_ROLL_GROUPS = ['Contributions/Employee'];
const DEFAULT_COMBINE_GROUPS_TEXT =
  'Adjustments: Adjustment (+), Adjustment (-)\nRealized/Unrealized Gain Loss: Realized Gain/(Loss), Unrealized Gain/(Loss)';

export default function ProcessingScreen({ files, onBack }) {
  const [rows, setRows] = useState(() =>
    files.map((f, index) => {
      const firstCol = f.columns?.[0];
      return {
        ...f,
        internal_name: `plan${index + 1}`,
        display_name: `File ${index + 1}`,
        target_sheet_name: guessTargetSheetName(f),
        use_for_summary: false,
        index_col: resolveDisplayHeader(firstCol),
        sum_cols: f.columns?.filter(c => c.numeric).map(resolveDisplayHeader) || [],
        summary_sheet_name: defaultSummarySheetName(f, index),
        group_headers_text: DEFAULT_GROUP_HEADERS.join('\n'),
        section_groups_text: DEFAULT_SECTION_GROUPS.join('\n'),
        roll_groups_text: DEFAULT_ROLL_GROUPS.join('\n'),
        combine_groups_text: DEFAULT_COMBINE_GROUPS_TEXT
      };
    })
  );

  const [templatePath, setTemplatePath] = useState('');
  const [reportingDate, setReportingDate] = useState('');
  const [running, setRunning] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);

  useEffect(() => {
    const today = new Date();
    setReportingDate(`${today.getMonth() + 1}/${today.getDate()}/${today.getFullYear()}`);
  }, []);

  const selectedSummaryCount = useMemo(() => rows.filter(row => row.use_for_summary).length, [rows]);

  function updateRow(rowId, key, value) {
    setRows(current => current.map(r => (r.rowId === rowId ? { ...r, [key]: value } : r)));
  }

  function toggleSummaryRow(rowId, checked) {
    setRows(current =>
      current.map(r =>
        r.rowId === rowId
          ? {
              ...r,
              use_for_summary: checked,
              sum_cols: checked
                ? (r.sum_cols.length ? r.sum_cols : r.columns?.filter(c => c.numeric).map(resolveDisplayHeader) || [])
                : r.sum_cols
            }
          : r
      )
    );
  }

  async function handlePickTemplate() {
    const picked = await window.api.selectTemplateFile();
    if (picked) setTemplatePath(picked);
  }

  function buildPayloadRows() {
    return rows.map((r, index) => {
      const toPayload = Object.fromEntries(
        (r.columns || []).map(c => [resolveDisplayHeader(c), resolvePayloadHeader(c)])
      );

      return {
        row_id: r.rowId,
        internal_name: r.internal_name,
        validated_path: r.validatedPath,
        target_sheet_name: r.target_sheet_name,
        use_for_summary: r.use_for_summary,
        index_col: toPayload[r.index_col] ?? r.index_col,
        sum_cols: r.sum_cols.filter(Boolean).map(s => toPayload[s] ?? s),
        summary_config: r.use_for_summary
          ? {
              sheet_name: sanitizeSheetName(r.summary_sheet_name, `Summary ${index + 1}`),
              group_headers: parseLines(r.group_headers_text),
              section_groups: parseLines(r.section_groups_text),
              roll_groups: parseLines(r.roll_groups_text),
              combine_groups: parseCombineGroups(r.combine_groups_text)
            }
          : null
      };
    });
  }

  async function handleRun() {
    setError('');
    setResult(null);

    if (!templatePath) {
      setError('Select a template workbook first.');
      return;
    }

    const missingTarget = rows.find(r => !r.target_sheet_name.trim());
    if (missingTarget) {
      setError(`File ${missingTarget.display_name} needs a target sheet name.`);
      return;
    }

    const selectedRows = rows.filter(r => r.use_for_summary);
    for (const row of selectedRows) {
      if (!row.index_col || row.sum_cols.length === 0) {
        setError(`File ${row.display_name}: pick both a description column and at least one numeric column.`);
        return;
      }
      if (!sanitizeSheetName(row.summary_sheet_name)) {
        setError(`File ${row.display_name}: summary sheet name is required.`);
        return;
      }
    }

    const summaryNames = selectedRows.map(r => sanitizeSheetName(r.summary_sheet_name).toLowerCase());
    if (new Set(summaryNames).size !== summaryNames.length) {
      setError('Summary sheet names must be unique across selected files.');
      return;
    }

    setRunning(true);
    try {
      const payload = {
        template_path: templatePath,
        reporting_date: reportingDate,
        rows: buildPayloadRows()
      };

      const response = await window.api.runTrialBalance(payload);
      if (!response.success) {
        throw new Error(response.message || 'Trial balance generation failed.');
      }
      setResult(response);
    } catch (err) {
      setError(err.message || 'Trial balance generation failed.');
    } finally {
      setRunning(false);
    }
  }

  async function openOutput() {
    if (result?.outputPath) {
      await window.api.openReport(result.outputPath);
    }
  }

  const summaries = result?.summaries || (result?.summary ? [{ summarySheetName: 'Summary', totals: result.summary }] : []);

  return (
    <div className="page" style={{ justifyContent: 'flex-start', paddingTop: 40 }}>
      <div className="steps">
        <div className="step"><div className="step-num">1</div><span>Select Files</span></div>
        <div className="step-line" />
        <div className="step"><div className="step-num">2</div><span>Map Sheets</span></div>
        <div className="step-line" />
        <div className="step"><div className="step-num">3</div><span>Validate</span></div>
        <div className="step-line" />
        <div className="step active"><div className="step-num">4</div><span>Process</span></div>
      </div>

      <div className="container">
        <div className="card-icon">⚙️</div>
        <h1>Build Trial Balance</h1>
        <p className="hint">
          Validated sheets below were written to <code>converted/</code> after passing validation.
          Map each one to a destination tab in the template workbook, then optionally select any
          number of files to build separate summaries with separate logic.
        </p>

        <div style={{ display: 'flex', gap: 12, alignItems: 'end', flexWrap: 'wrap', marginTop: 18 }}>
          <Field label="Template workbook">
            <button type="button" className="btn btn-ghost" onClick={handlePickTemplate} style={{ minWidth: 220 }}>
              {templatePath ? 'Change Template' : 'Select Template Workbook *'}
            </button>
          </Field>

          {templatePath && (
            <span style={{ fontSize: 12, color: 'var(--primary)', maxWidth: 320, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {templatePath}
            </span>
          )}

          <Field label="Reporting date (1. Procedures!A2)">
            <input value={reportingDate} onChange={e => setReportingDate(e.target.value)} style={inputStyle(180)} />
          </Field>

          <div style={{ fontSize: 12, color: 'var(--fg-muted)', paddingBottom: 8 }}>
            Summary files selected: <strong>{selectedSummaryCount}</strong>
          </div>

          <button className="btn btn-ghost" onClick={onBack} disabled={running}>← Back</button>
          <button className="btn btn-primary" onClick={handleRun} disabled={running}>
            {running ? 'Running...' : 'Run Trial Balance'}
          </button>

          {result?.outputPath && (
            <button className="btn btn-ghost" onClick={openOutput}>Open Output</button>
          )}
        </div>

        {rows.map((row, index) => (
          <div
            key={row.rowId}
            style={{ marginTop: 22, padding: 16, background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border)', borderRadius: 12 }}
          >
            <h3 style={{ marginBottom: 10 }}>
              {row.display_name} — {row.fileName} — {row.sheetName}
            </h3>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 }}>
              <Field label="Target sheet name (in template)">
                <input
                  value={row.target_sheet_name}
                  onChange={e => updateRow(row.rowId, 'target_sheet_name', e.target.value)}
                  style={inputStyle()}
                />
              </Field>

              <Field label="Description column (for this summary)">
                <select
                  value={row.index_col}
                  onChange={e => updateRow(row.rowId, 'index_col', e.target.value)}
                  style={inputStyle()}
                  disabled={!row.use_for_summary}
                >
                  <option value="">—</option>
                  {(row.columns || []).map(c => {
                    const displayName = resolveDisplayHeader(c);
                    return <option key={c.column} value={displayName}>{displayName}</option>;
                  })}
                </select>
              </Field>

              <Field label="Numeric columns (for this summary)">
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6, background: 'var(--bg)', padding: 8, borderRadius: 7, border: '1px solid var(--border)' }}>
                  {(row.columns || []).filter(c => c.numeric).map(c => {
                    const displayName = resolveDisplayHeader(c);
                    const isChecked = row.sum_cols.includes(displayName);
                    return (
                      <label key={c.column} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, opacity: row.use_for_summary ? 1 : 0.5 }}>
                        <input
                          type="checkbox"
                          checked={isChecked}
                          disabled={!row.use_for_summary}
                          onChange={e => {
                            const newCols = e.target.checked
                              ? [...row.sum_cols, displayName]
                              : row.sum_cols.filter(x => x !== displayName);
                            updateRow(row.rowId, 'sum_cols', newCols);
                          }}
                        />
                        {displayName}
                      </label>
                    );
                  })}
                </div>
              </Field>

              <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: 'var(--fg-muted)', alignSelf: 'end', paddingBottom: 8 }}>
                <input
                  type="checkbox"
                  checked={row.use_for_summary}
                  onChange={e => toggleSummaryRow(row.rowId, e.target.checked)}
                />
                Build separate summary from this file
              </label>
            </div>

            {row.use_for_summary && (
              <div style={{ marginTop: 16, padding: 14, background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border)', borderRadius: 10 }}>
                <h4 style={{ marginBottom: 12 }}>Summary logic for {row.display_name}</h4>

                <Field label="Summary sheet name">
                  <input
                    value={row.summary_sheet_name}
                    onChange={e => updateRow(row.rowId, 'summary_sheet_name', e.target.value)}
                    style={{ ...inputStyle(), marginBottom: 14 }}
                    placeholder={`Summary ${index + 1}`}
                  />
                </Field>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 14 }}>
                  <Field label="Group headers (one per line)">
                    <textarea
                      value={row.group_headers_text}
                      onChange={e => updateRow(row.rowId, 'group_headers_text', e.target.value)}
                      rows={6}
                      style={{ ...inputStyle(), resize: 'vertical' }}
                    />
                  </Field>

                  <Field label="Section groups (one per line)">
                    <textarea
                      value={row.section_groups_text}
                      onChange={e => updateRow(row.rowId, 'section_groups_text', e.target.value)}
                      rows={6}
                      style={{ ...inputStyle(), resize: 'vertical' }}
                    />
                  </Field>

                  <Field label="Roll groups (one per line)">
                    <textarea
                      value={row.roll_groups_text}
                      onChange={e => updateRow(row.rowId, 'roll_groups_text', e.target.value)}
                      rows={6}
                      style={{ ...inputStyle(), resize: 'vertical' }}
                    />
                  </Field>

                  <Field label='Combine groups ("Output: A, B" per line)'>
                    <textarea
                      value={row.combine_groups_text}
                      onChange={e => updateRow(row.rowId, 'combine_groups_text', e.target.value)}
                      rows={6}
                      style={{ ...inputStyle(), resize: 'vertical' }}
                    />
                  </Field>
                </div>
              </div>
            )}
          </div>
        ))}

        {error && <div className="status" style={{ marginTop: 20 }}>{error}</div>}

        {result && (
          <div style={{ marginTop: 24, padding: 16, background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border)', borderRadius: 12 }}>
            <div className="status" style={{ marginBottom: 10 }}>
              Saved to: {result.outputPath}
            </div>

            {result.log?.map((line, idx) => (
              <div key={idx} style={{ fontSize: 12, color: 'var(--fg-muted)', marginBottom: 4 }}>{line}</div>
            ))}

            {summaries.map((summaryRun, idx) => (
              <div key={`${summaryRun.summarySheetName}-${idx}`} style={{ marginTop: 16 }}>
                <h4 style={{ marginBottom: 8 }}>
                  {summaryRun.summarySheetName}
                  {summaryRun.rowId ? ` — ${summaryRun.rowId}` : ''}
                </h4>
                <table>
                  <thead>
                    <tr><th>Group</th><th>Total</th></tr>
                  </thead>
                  <tbody>
                    {Object.entries(summaryRun.totals || {}).map(([k, v]) => (
                      <tr key={k}><td>{k}</td><td>{v}</td></tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
