# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: python_backend/converter.py

from __future__ import annotations

import datetime
import os
from copy import copy
from typing import Dict, Optional, Tuple

import openpyxl
import xlrd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


_H_ALIGN = {
    0: "general", 1: "left",   2: "center", 3: "right",
    4: "fill",    5: "justify", 6: "centerContinuous", 7: "distributed",
}

_V_ALIGN = {
    0: "top", 1: "center", 2: "bottom", 3: "justify", 4: "distributed",
}

_BORDER_STYLE = {
    0: None,       1: "thin",           2: "medium",          3: "dashed",
    4: "dotted",   5: "thick",          6: "double",          7: "hair",
    8: "mediumDashed", 9: "dashDot",   10: "mediumDashDot",  11: "dashDotDot",
    12: "mediumDashDotDot", 13: "slantDashDot",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sanitize(value: str) -> str:
    return value.replace("\n", " ").replace("\t", " ").strip()


def _is_blank(value) -> bool:
    return value is None or (isinstance(value, str) and value.strip() == "")


def _remove_empty_columns(ws) -> None:
    """Single-pass scan — O(rows) instead of O(cols × rows)."""
    if not ws.max_column:
        return

    # Collect all columns that have at least one non-blank value in one pass
    non_empty: set[int] = set()
    for row in ws.iter_rows():
        for cell in row:
            if not _is_blank(cell.value):
                non_empty.add(cell.column)

    cols_to_delete = [
        c for c in range(1, ws.max_column + 1) if c not in non_empty
    ]
    for col_idx in reversed(cols_to_delete):
        ws.delete_cols(col_idx)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def convert_to_xlsx(file_path: str, output_dir: str) -> str:
    base_name   = os.path.splitext(os.path.basename(file_path))[0]
    output_path = os.path.join(output_dir, f"{base_name}.xlsx")
    ext         = os.path.splitext(file_path)[1].lower()

    if ext in (".xlsx", ".xlsm"):
        _convert_modern(file_path, output_path)
    elif ext == ".xls":
        _convert_xls(file_path, output_path)
    else:
        raise ValueError(f"Unsupported file extension: {ext}")

    return output_path


# ---------------------------------------------------------------------------
# Modern (.xlsx / .xlsm) path
# ---------------------------------------------------------------------------

def _convert_modern(file_path: str, output_path: str) -> None:
    wb = load_workbook(file_path, keep_vba=False)
    for ws in wb.worksheets:
        _flatten_openpyxl_merged_ranges(ws)
        _sanitize_sheet_strings(ws)
        _remove_empty_columns(ws)
    wb.save(output_path)


def _sanitize_sheet_strings(ws) -> None:
    for row in ws.iter_rows():
        for cell in row:
            if isinstance(cell.value, str):
                cell.value = _sanitize(cell.value)


def _flatten_openpyxl_merged_ranges(ws) -> None:
    """
    Merge rules:
      - Horizontal span  → value only in anchor column; sibling columns stay blank.
      - Vertical span    → value propagated down every row, but only in anchor column.
      - Combined span    → each row in range gets value at min_col; other cols stay blank.
    """
    for merged_range in list(ws.merged_cells.ranges):
        min_col = merged_range.min_col
        min_row = merged_range.min_row
        max_row = merged_range.max_row

        source = ws.cell(row=min_row, column=min_col)

        # Snapshot styles before unmerge clears them
        src_value          = source.value
        src_font           = copy(source.font)
        src_fill           = copy(source.fill)
        src_border         = copy(source.border)
        src_alignment      = copy(source.alignment)
        src_number_format  = source.number_format
        src_protection     = copy(source.protection)

        ws.unmerge_cells(str(merged_range))

        # Write value to every row in the vertical span, anchor column only.
        # Horizontal siblings (col > min_col) intentionally stay blank.
        for row_idx in range(min_row, max_row + 1):
            target                = ws.cell(row=row_idx, column=min_col)
            target.value          = src_value
            target.font           = copy(src_font)
            target.fill           = copy(src_fill)
            target.border         = copy(src_border)
            target.alignment      = copy(src_alignment)
            target.number_format  = src_number_format
            target.protection     = copy(src_protection)


# ---------------------------------------------------------------------------
# Legacy (.xls) path
# ---------------------------------------------------------------------------

def _convert_xls(file_path: str, output_path: str) -> None:
    xls_wb = xlrd.open_workbook(file_path, formatting_info=True)
    xlsx_wb = openpyxl.Workbook()
    xlsx_wb.remove(xlsx_wb.active)

    for sheet_idx in range(xls_wb.nsheets):
        xls_ws   = xls_wb.sheet_by_index(sheet_idx)
        xlsx_ws  = xlsx_wb.create_sheet(title=xls_wb.sheet_names()[sheet_idx])

        merge_anchor_map = _build_merged_anchor_map(xls_ws)

        # Pre-build style cache keyed by xf_index — avoids recomputing identical
        # font/fill/border/alignment objects for every cell sharing the same format.
        style_cache: Dict[int, Tuple] = {}

        # Bulk-read all rows upfront — faster than per-cell xls_ws.cell() calls
        all_rows = [xls_ws.row(r) for r in range(xls_ws.nrows)]

        for row_idx, xls_row in enumerate(all_rows):
            row_info = xls_ws.rowinfo_map.get(row_idx)
            if row_info and row_info.height:
                xlsx_ws.row_dimensions[row_idx + 1].height = row_info.height / 20.0

            for col_idx, src_cell in enumerate(xls_row):
                # For merged cells: resolve to anchor; for non-merged: use cell as-is
                anchor = merge_anchor_map.get((row_idx, col_idx))
                if anchor is not None:
                    src_row, src_col = anchor
                    src_cell = all_rows[src_row][src_col]

                dst_cell       = xlsx_ws.cell(row=row_idx + 1, column=col_idx + 1)
                dst_cell.value = _convert_cell_value(src_cell, xls_wb)
                _apply_xlrd_style_cached(dst_cell, src_cell, xls_wb, style_cache)

        for col_idx in range(xls_ws.ncols):
            col_info = xls_ws.colinfo_map.get(col_idx)
            if col_info and col_info.width > 0:
                xlsx_ws.column_dimensions[get_column_letter(col_idx + 1)].width = (
                    col_info.width / 256.0
                )

        _remove_empty_columns(xlsx_ws)

    xlsx_wb.save(output_path)


def _build_merged_anchor_map(
    xls_ws,
) -> Dict[Tuple[int, int], Tuple[int, int]]:
    """
    Merge rules (mirrors _flatten_openpyxl_merged_ranges):
      - Every row in the vertical span maps to (rlo, clo) — vertical propagation.
      - Only the anchor column (clo) is mapped; sibling columns (clo+1 … chi-1)
        resolve to themselves and stay blank — no horizontal duplication.
    """
    anchor_map: Dict[Tuple[int, int], Tuple[int, int]] = {}
    for rlo, rhi, clo, chi in xls_ws.merged_cells:  # noqa: F841 (chi unused by design)
        for row_idx in range(rlo, rhi):
            # Anchor column only — horizontal siblings excluded intentionally
            anchor_map[(row_idx, clo)] = (rlo, clo)
    return anchor_map


# ---------------------------------------------------------------------------
# Cell value conversion
# ---------------------------------------------------------------------------

def _convert_cell_value(cell: xlrd.sheet.Cell, wb: xlrd.Book):
    ctype, value = cell.ctype, cell.value

    if ctype == xlrd.XL_CELL_DATE:
        try:
            parts = xlrd.xldate_as_tuple(value, wb.datemode)
            return (
                datetime.time(parts[3], parts[4], int(parts[5]))
                if parts[0] == 0
                else datetime.datetime(*parts[:3], *parts[3:5], int(parts[5]))
            )
        except Exception:
            return value

    if ctype == xlrd.XL_CELL_BOOLEAN:
        return bool(value)

    if ctype == xlrd.XL_CELL_ERROR:
        return None

    if isinstance(value, str):
        return _sanitize(value)

    return value


# ---------------------------------------------------------------------------
# Style application — with xf_index caching
# ---------------------------------------------------------------------------

def _apply_xlrd_style_cached(
    dst_cell,
    src_cell: xlrd.sheet.Cell,
    wb: xlrd.Book,
    cache: Dict[int, Tuple],
) -> None:
    """
    Resolve style once per unique xf_index and reuse from cache.
    Cells sharing the same format (very common in structured sheets) skip
    all build_* calls after the first occurrence.
    """
    xf_idx = getattr(src_cell, "xf_index", None)
    if xf_idx is None or xf_idx >= len(wb.xf_list):
        return

    if xf_idx not in cache:
        xf = wb.xf_list[xf_idx]
        cache[xf_idx] = (
            _get_format_string_by_xf(wb, xf) or "General",
            _build_font(wb, xf),
            _build_fill(wb, xf),
            _build_border(wb, xf),
            _build_alignment(xf),
        )

    fmt, font, fill, border, alignment = cache[xf_idx]
    dst_cell.number_format = fmt
    dst_cell.font          = font
    dst_cell.fill          = fill
    dst_cell.border        = border
    dst_cell.alignment     = alignment


def _get_format_string_by_xf(wb: xlrd.Book, xf) -> Optional[str]:
    fmt = wb.format_map.get(xf.format_key)
    if not fmt or not fmt.format_str:
        return None
    return None if fmt.format_str.upper() == "GENERAL" else fmt.format_str


def _build_font(wb: xlrd.Book, xf) -> Font:
    font  = wb.font_list[xf.font_index]
    color = _xlrd_color_to_hex(wb, getattr(font, "colour_index", None))
    return Font(
        name=getattr(font, "name", None),
        size=(getattr(font, "height", 200) / 20.0) if getattr(font, "height", None) else None,
        bold=bool(getattr(font, "bold", 0)),
        italic=bool(getattr(font, "italic", 0)),
        underline="single" if bool(getattr(font, "underlined", 0)) else None,
        strike=bool(getattr(font, "struck_out", 0)),
        color=color,
    )


def _build_fill(wb: xlrd.Book, xf) -> PatternFill:
    bg      = xf.background
    pattern = getattr(bg, "fill_pattern", 0)

    if not pattern:
        return PatternFill(fill_type=None)

    fg = _xlrd_color_to_hex(wb, getattr(bg, "pattern_colour_index", None))
    if not fg:
        fg = _xlrd_color_to_hex(wb, getattr(bg, "background_colour_index", None))

    return PatternFill(fill_type="solid", fgColor=fg, bgColor=fg) if fg else PatternFill(fill_type=None)


def _build_border(wb: xlrd.Book, xf) -> Border:
    b = xf.border
    return Border(
        left=_build_side(wb, b.left_line_style,   b.left_colour_index),
        right=_build_side(wb, b.right_line_style,  b.right_colour_index),
        top=_build_side(wb, b.top_line_style,    b.top_colour_index),
        bottom=_build_side(wb, b.bottom_line_style, b.bottom_colour_index),
    )


def _build_side(wb: xlrd.Book, line_style: int, colour_index: int) -> Side:
    return Side(
        style=_BORDER_STYLE.get(line_style),
        color=_xlrd_color_to_hex(wb, colour_index),
    )


def _build_alignment(xf) -> Alignment:
    alignment = xf.alignment
    rotation  = getattr(alignment, "rotation", 0)
    if rotation == 255:
        rotation = 0
    return Alignment(
        horizontal=_H_ALIGN.get(getattr(alignment, "hor_align", 0)),
        vertical=_V_ALIGN.get(getattr(alignment, "vert_align", 2)),
        wrap_text=bool(getattr(alignment, "text_wrapped", 0)),
        shrink_to_fit=bool(getattr(alignment, "shrink_to_fit", 0)),
        indent=getattr(alignment, "indent_level", 0),
        text_rotation=rotation,
    )


def _xlrd_color_to_hex(wb: xlrd.Book, color_index) -> Optional[str]:
    if color_index is None:
        return None
    color_map = getattr(wb, "colour_map", None)
    if not color_map:
        return None
    rgb = color_map.get(color_index)
    if not rgb or not isinstance(rgb, tuple) or len(rgb) < 3:
        return None
    r, g, b = rgb[:3]
    return f"{r:02X}{g:02X}{b:02X}"
