# filename: python_backend/excel_validation.py
# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations

import json
import sys
from copy import copy
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
from converter import convert_to_xlsx
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter


@dataclass
class ColumnRule:
    column: str
    expected_header: str
    numeric: bool = False


@dataclass
class FileRule:
    file_path: str
    sheet_name: str
    header_row: int
    data_start_row: int
    data_end_row: int
    start_col: str
    end_col: str
    number_of_columns: int = 0
    columns: list[ColumnRule] = field(default_factory=list)
    row_id: str = ""


def col_letter_to_index(col: str) -> int:
    text = str(col or "").strip().upper()
    if not text:
        raise ValueError("Column letter cannot be blank.")

    value = 0
    for char in text:
        if not ("A" <= char <= "Z"):
            raise ValueError(f"Invalid column letter: {col}")
        value = value * 26 + (ord(char) - 64)
    return value


def normalize_text(value: Any) -> str:
    if value is None:
        return ""
    if pd.isna(value):
        return ""
    text = str(value)
    return text.replace("\n", " ").replace("\t", " ").strip()


def read_block(
    file_path: str,
    sheet_name: str,
    header_row: int,
    data_end_row: int,
    start_idx: int,
    end_idx: int,
) -> pd.DataFrame:
    nrows = data_end_row - header_row + 1

    full = pd.read_excel(
        file_path,
        sheet_name=sheet_name,
        header=None,
        skiprows=header_row - 1,
        nrows=nrows,
        dtype=object,
    )

    width = end_idx - start_idx + 1
    columns = {}

    for offset in range(width):
        col_pos = (start_idx + offset) - 1
        if col_pos < full.shape[1]:
            columns[offset] = full.iloc[:, col_pos].reset_index(drop=True)
        else:
            columns[offset] = pd.Series([None] * len(full))

    return pd.DataFrame(columns)


def make_result(rule: FileRule) -> dict[str, Any]:
    return {
        "file_path": rule.file_path,
        "sheet_name": rule.sheet_name,
        "row_id": rule.row_id,
        "file_exists": False,
        "sheet_exists": False,
        "range_read": False,
        "status": "FAIL",
        "errors": [],
        "columns": [],
        "validated_path": None,
    }


def validate_rule(rule: FileRule) -> dict[str, Any]:
    result = make_result(rule)
    path = Path(rule.file_path)

    if not path.exists():
        result["errors"].append("File not found.")
        return result
    result["file_exists"] = True

    try:
        excel_file = pd.ExcelFile(path)
    except Exception as exc:
        result["errors"].append(f"Unable to open workbook: {exc}")
        return result

    if rule.sheet_name not in excel_file.sheet_names:
        result["errors"].append("Sheet not found.")
        return result
    result["sheet_exists"] = True

    if min(rule.header_row, rule.data_start_row, rule.data_end_row) < 1:
        result["errors"].append("Row numbers must be greater than zero.")
        return result

    if rule.header_row > rule.data_start_row:
        result["errors"].append("header_row cannot be greater than data_start_row.")
        return result

    if rule.data_start_row > rule.data_end_row:
        result["errors"].append("data_start_row cannot be greater than data_end_row.")
        return result

    if rule.number_of_columns < 1:
        result["errors"].append("number_of_columns must be at least 1.")
        return result

    if len(rule.columns) != rule.number_of_columns:
        result["errors"].append(
            f"Expected {rule.number_of_columns} column mapping rows, found {len(rule.columns)}."
        )
        return result

    try:
        start_idx = col_letter_to_index(rule.start_col)
        end_idx = col_letter_to_index(rule.end_col)
    except Exception as exc:
        result["errors"].append(str(exc))
        return result

    if start_idx > end_idx:
        result["errors"].append(
            f"Start column cannot be after End column. You entered {rule.start_col}:{rule.end_col}."
        )
        return result

    available_column_count = end_idx - start_idx + 1
    if rule.number_of_columns > available_column_count:
        result["errors"].append(
            f"Number of headers out of bound. Selected range {rule.start_col}:{rule.end_col} "
            f"contains only {available_column_count} columns, but number_of_columns is "
            f"{rule.number_of_columns}."
        )
        return result

    try:
        raw = read_block(
            str(path),
            rule.sheet_name,
            rule.header_row,
            rule.data_end_row,
            start_idx,
            end_idx,
        )
    except Exception as exc:
        result["errors"].append(f"Unable to read configured range: {exc}")
        return result

    if raw.empty:
        result["errors"].append("Configured range returned no data.")
        return result

    result["range_read"] = True
    header_values = raw.iloc[0].tolist()
    body_start = rule.data_start_row - rule.header_row
    body_end = rule.data_end_row - rule.header_row
    body = raw.iloc[body_start : body_end + 1].reset_index(drop=True)

    seen_columns = set()

    for column_rule in rule.columns:
        col_name = normalize_text(column_rule.column).upper()
        expected_header = normalize_text(column_rule.expected_header)
        col_result = {
            "column": col_name,
            "expected_header": expected_header,
            "actual_header": None,
            "header_match": False,
            "non_blank_count": 0,
            "numeric": column_rule.numeric,
            "numeric_sum": None,
        }

        if not col_name:
            result["errors"].append("Mapped column cannot be blank.")
            result["columns"].append(col_result)
            continue

        if not expected_header:
            col_result["expected_header"] = ""
            result["columns"].append(col_result)
            continue

        if col_name in seen_columns:
            result["errors"].append(f"Duplicate mapped column: {col_name}.")
            result["columns"].append(col_result)
            continue
        seen_columns.add(col_name)

        try:
            abs_idx = col_letter_to_index(col_name)
        except Exception:
            result["errors"].append(f"Invalid mapped column: {col_name}")
            result["columns"].append(col_result)
            continue

        rel_idx = abs_idx - start_idx
        if rel_idx < 0 or rel_idx >= len(header_values):
            result["errors"].append(
                f"Column {col_name} is outside range {rule.start_col}:{rule.end_col}."
            )
            result["columns"].append(col_result)
            continue

        actual_header = normalize_text(header_values[rel_idx])
        header_match = actual_header == expected_header
        col_result["actual_header"] = actual_header
        col_result["header_match"] = header_match

        if not header_match:
            result["errors"].append(
                f"Header mismatch at {col_name}{rule.header_row}: expected "
                f"'{expected_header}', found '{actual_header}'."
            )

        series = body.iloc[:, rel_idx]
        mask = series.notna() & series.astype(str).str.strip().ne("")
        col_result["non_blank_count"] = int(mask.sum())

        if column_rule.numeric:
            numeric_series = pd.to_numeric(series, errors="coerce")
            if numeric_series.notna().any():
                col_result["numeric_sum"] = float(numeric_series.sum())

        result["columns"].append(col_result)

    result["status"] = "PASS" if not result["errors"] else "FAIL"
    return result


def _copy_cell_with_style(source_cell, target_cell) -> None:
    target_cell.value = source_cell.value

    if source_cell.has_style:
        target_cell.font = copy(source_cell.font)
        target_cell.fill = copy(source_cell.fill)
        target_cell.border = copy(source_cell.border)
        target_cell.alignment = copy(source_cell.alignment)
        target_cell.number_format = source_cell.number_format
        target_cell.protection = copy(source_cell.protection)

    if source_cell.hyperlink:
        target_cell._hyperlink = copy(source_cell.hyperlink)

    if source_cell.comment:
        target_cell.comment = copy(source_cell.comment)


def _resolve_source_for_formatted_export(file_path: str, converted_dir: str) -> str:
    path = Path(file_path)
    if path.suffix.lower() == ".xls":
        return convert_to_xlsx(str(path), converted_dir)
    return str(path)


def _copy_validated_range_with_formatting(rule: FileRule, source_path: str, output_path: str) -> str:
    start_idx = col_letter_to_index(rule.start_col)
    end_idx = col_letter_to_index(rule.end_col)

    source_wb = load_workbook(source_path)
    if rule.sheet_name not in source_wb.sheetnames:
        source_wb.close()
        raise ValueError(f"Sheet '{rule.sheet_name}' not found in formatted source workbook.")

    source_ws = source_wb[rule.sheet_name]

    target_wb = Workbook()
    target_ws = target_wb.active
    target_ws.title = (rule.sheet_name or "Sheet1")[:31]

    for source_col_idx in range(start_idx, end_idx + 1):
        target_col_idx = source_col_idx - start_idx + 1
        source_col_letter = get_column_letter(source_col_idx)
        target_col_letter = get_column_letter(target_col_idx)

        source_dim = source_ws.column_dimensions[source_col_letter]
        target_dim = target_ws.column_dimensions[target_col_letter]

        if source_dim.width is not None:
            target_dim.width = source_dim.width
        target_dim.hidden = source_dim.hidden
        target_dim.bestFit = source_dim.bestFit

    for source_row_idx in range(rule.header_row, rule.data_end_row + 1):
        target_row_idx = source_row_idx - rule.header_row + 1
        source_dim = source_ws.row_dimensions[source_row_idx]
        target_dim = target_ws.row_dimensions[target_row_idx]

        if source_dim.height is not None:
            target_dim.height = source_dim.height
        target_dim.hidden = source_dim.hidden

        for source_col_idx in range(start_idx, end_idx + 1):
            target_col_idx = source_col_idx - start_idx + 1
            source_cell = source_ws.cell(row=source_row_idx, column=source_col_idx)
            target_cell = target_ws.cell(row=target_row_idx, column=target_col_idx)
            _copy_cell_with_style(source_cell, target_cell)

    for merged_range in source_ws.merged_cells.ranges:
        min_col, min_row, max_col, max_row = merged_range.bounds
        fully_inside = (
            min_row >= rule.header_row
            and max_row <= rule.data_end_row
            and min_col >= start_idx
            and max_col <= end_idx
        )
        if fully_inside:
            target_ws.merge_cells(
                start_row=min_row - rule.header_row + 1,
                start_column=min_col - start_idx + 1,
                end_row=max_row - rule.header_row + 1,
                end_column=max_col - start_idx + 1,
            )

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    target_wb.save(output)

    source_wb.close()
    target_wb.close()
    return str(output.resolve())


def write_validated_range(rule: FileRule, converted_dir: str | None) -> str | None:
    if not converted_dir:
        return None

    out_dir = Path(converted_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    safe_name = (rule.row_id or rule.sheet_name or "sheet").strip().replace(" ", "_")
    output_path = out_dir / f"{safe_name}_validated.xlsx"

    try:
        source_path = _resolve_source_for_formatted_export(rule.file_path, str(out_dir))
        return _copy_validated_range_with_formatting(rule, source_path, str(output_path))
    except Exception:
        return None


def validate_payload(payload: dict[str, Any]) -> dict[str, Any]:
    rules = []
    for item in payload.get("files", []):
        columns = [ColumnRule(**col) for col in item.get("columns", [])]
        rules.append(
            FileRule(
                file_path=item.get("file_path", ""),
                sheet_name=item.get("sheet_name", ""),
                header_row=int(item.get("header_row", 0) or 0),
                data_start_row=int(item.get("data_start_row", 0) or 0),
                data_end_row=int(item.get("data_end_row", 0) or 0),
                start_col=item.get("start_col", ""),
                end_col=item.get("end_col", ""),
                number_of_columns=int(item.get("number_of_columns", 0) or 0),
                columns=columns,
                row_id=item.get("row_id", ""),
            )
        )

    results = [validate_rule(rule) for rule in rules]
    overall_status = "PASS" if results and all(item["status"] == "PASS" for item in results) else "FAIL"

    if overall_status == "PASS":
        converted_dir = payload.get("converted_dir")
        for rule, result in zip(rules, results):
            result["validated_path"] = write_validated_range(rule, converted_dir)

    return {
        "overall_status": overall_status,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "file_count": len(results),
        "results": results,
    }


def style_sheet(ws) -> None:
    fill = PatternFill(fill_type="solid", fgColor="D9EAD3")
    font = Font(bold=True)

    for cell in ws[1]:
        cell.fill = fill
        cell.font = font

    for col in ws.columns:
        width = max(len(str(cell.value or "")) for cell in col) + 2
        ws.column_dimensions[col[0].column_letter].width = min(width, 50)


def write_excel_report(validation_output: dict[str, Any], report_path: str) -> str:
    wb = Workbook()

    ws = wb.active
    ws.title = "Summary"
    ws.append(["Metric", "Value"])
    ws.append(["Overall Status", validation_output["overall_status"]])
    ws.append(["Generated At", validation_output["generated_at"]])
    ws.append(["File Count", validation_output["file_count"]])
    style_sheet(ws)

    ws = wb.create_sheet("File Checks")
    ws.append(["File Path", "Sheet", "File Exists", "Sheet Exists", "Range Read", "Status", "Errors"])
    for item in validation_output["results"]:
        ws.append([
            item["file_path"],
            item["sheet_name"],
            item["file_exists"],
            item["sheet_exists"],
            item["range_read"],
            item["status"],
            " | ".join(item["errors"]),
        ])
    style_sheet(ws)

    ws = wb.create_sheet("Column Checks")
    ws.append([
        "File Path",
        "Sheet",
        "Column",
        "Expected Header",
        "Actual Header",
        "Header Match",
        "Non Blank Count",
        "Numeric",
        "Numeric Sum",
    ])
    for item in validation_output["results"]:
        for col in item["columns"]:
            ws.append([
                item["file_path"],
                item["sheet_name"],
                col["column"],
                col["expected_header"],
                col["actual_header"],
                col["header_match"],
                col["non_blank_count"],
                col["numeric"],
                col["numeric_sum"],
            ])
    style_sheet(ws)

    output = Path(report_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output)
    return str(output.resolve())


def build_ui_response(validation_output: dict[str, Any], report_path: str | None) -> dict[str, Any]:
    files = []

    for item in validation_output["results"]:
        files.append({
            "rowId": item.get("row_id"),
            "filePath": item["file_path"],
            "fileName": Path(item["file_path"]).name,
            "sheetName": item["sheet_name"],
            "status": item["status"],
            "fileExists": item["file_exists"],
            "sheetExists": item["sheet_exists"],
            "rangeRead": item["range_read"],
            "errors": item["errors"],
            "validatedPath": item.get("validated_path"),
            "columns": [
                {
                    "column": col["column"],
                    "expectedHeader": col["expected_header"],
                    "actualHeader": col["actual_header"],
                    "headerMatch": col["header_match"],
                    "nonBlankCount": col["non_blank_count"],
                    "numericSum": col["numeric_sum"],
                }
                for col in item["columns"]
            ],
        })

    return {
        "success": validation_output["overall_status"] == "PASS",
        "overallStatus": validation_output["overall_status"],
        "generatedAt": validation_output["generated_at"],
        "fileCount": validation_output["file_count"],
        "passedFiles": sum(1 for item in files if item["status"] == "PASS"),
        "failedFiles": sum(1 for item in files if item["status"] == "FAIL"),
        "reportPath": report_path,
        "files": files,
    }


def build_default_report_path(payload: dict[str, Any]) -> str:
    output_dir = payload.get("report_output_dir", ".")
    return str(Path(output_dir) / "validation_report.xlsx")


def main() -> None:
    try:
        payload = json.load(sys.stdin)
        validation_output = validate_payload(payload)

        report_path = None
        if payload.get("generate_excel_report"):
            report_path = write_excel_report(validation_output, build_default_report_path(payload))

        print(json.dumps(build_ui_response(validation_output, report_path)))
        sys.exit(0)
    except Exception as exc:
        print(json.dumps({
            "success": False,
            "overallStatus": "FAIL",
            "message": str(exc),
            "files": [],
        }))
        sys.exit(1)


if __name__ == "__main__":
    main()
