# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: python_backend/trial_balance.py

from __future__ import annotations

import json
import sys
from copy import copy
from pathlib import Path
from typing import Any

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill


INVALID_SHEET_CHARS = set(r'[]:*?/\ '[:-1] + '\\')


def clean_sheet_title(title: str | None, fallback: str) -> str:
    text = str(title or "").strip()
    text = "".join(" " if ch in INVALID_SHEET_CHARS else ch for ch in text)
    text = " ".join(text.split())
    return (text or fallback)[:31]


def unique_sheet_title(workbook, requested_title: str | None, fallback: str) -> str:
    base = clean_sheet_title(requested_title, fallback)
    if base not in workbook.sheetnames:
        return base

    counter = 2
    while True:
        suffix = f" ({counter})"
        candidate = f"{base[:31 - len(suffix)]}{suffix}"
        if candidate not in workbook.sheetnames:
            return candidate
        counter += 1


def setup_sheet_styling(target_sheet, note_text: str | None = None) -> None:
    if note_text:
        target_sheet["A1"] = note_text
        target_sheet["A1"].font = Font(name="Calibri", size=11, bold=True, color="0000FF")

    white_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
    no_border = Border()

    for row in target_sheet.iter_rows(
        min_row=1,
        max_row=target_sheet.max_row or 1,
        min_col=1,
        max_col=target_sheet.max_column or 1,
    ):
        for cell in row:
            cell.fill = white_fill
            cell.border = no_border


def copy_xlsx_to_sheet(
    xlsx_file_path: str,
    target_workbook,
    target_sheet_name: str,
    row_offset: int = 2,
) -> tuple[str | None, str | None, str | None]:
    try:
        source_wb = load_workbook(xlsx_file_path, data_only=False)
    except Exception as exc:
        return None, None, f"Unable to open validated file: {exc}"

    if not source_wb.sheetnames:
        return None, None, "Validated file has no sheets."

    source_sheet_name = source_wb.sheetnames[0]
    source_sheet = source_wb[source_sheet_name]
    actual_target_sheet_name = unique_sheet_title(target_workbook, target_sheet_name, "Imported Sheet")
    target_sheet = target_workbook.create_sheet(title=actual_target_sheet_name)

    for row in source_sheet.iter_rows():
        for cell in row:
            target_cell = target_sheet.cell(row=cell.row + row_offset, column=cell.column)
            target_cell.value = cell.value

            if cell.has_style:
                target_cell.font = copy(cell.font)
                target_cell.border = Border()
                target_cell.fill = PatternFill(fill_type=None)
                target_cell.number_format = cell.number_format
                target_cell.protection = copy(cell.protection)
                target_cell.alignment = copy(cell.alignment)

    for col_letter, col_dim in source_sheet.column_dimensions.items():
        target_sheet.column_dimensions[col_letter].width = col_dim.width

    for row_num, row_dim in source_sheet.row_dimensions.items():
        target_sheet.row_dimensions[row_num + row_offset].height = row_dim.height

    for merged_range in source_sheet.merged_cells.ranges:
        target_sheet.merge_cells(
            start_row=merged_range.min_row + row_offset,
            start_column=merged_range.min_col,
            end_row=merged_range.max_row + row_offset,
            end_column=merged_range.max_col,
        )

    setup_sheet_styling(
        target_sheet,
        note_text=(
            "D&T downloaded the below statement as part of the Audit Package along "
            "with the Limited Scope certification using our auditor's access."
        ),
    )

    return source_sheet_name, actual_target_sheet_name, None


def read_validated_df(xlsx_file_path: str, sheet_name: str) -> pd.DataFrame:
    return pd.read_excel(
        xlsx_file_path,
        sheet_name=sheet_name,
        engine="openpyxl",
        header=0,
        dtype=object,
    )


def summarize_hierarchical_df(
    df: pd.DataFrame,
    index_col: str,
    sum_cols: list[str],
    group_headers: list[str],
    section_groups: list[str],
    roll_groups: list[str],
    combine_groups: dict[str, list[str]],
    target_workbook,
    sheet_name: str,
    log: list[str],
) -> tuple[str | None, dict[str, float]]:
    df = df.copy()
    df.columns = [str(c).strip() for c in df.columns]
    index_col = str(index_col).strip()
    clean_sum_cols = [str(c).strip() for c in sum_cols]

    if index_col not in df.columns:
        log.append(f"Summary Error: Description column '{index_col}' not found. Available columns: {df.columns.tolist()}")
        return None, {}

    valid_sum_cols = [c for c in clean_sum_cols if c in df.columns]
    if not valid_sum_cols:
        log.append(f"Summary Error: No numeric columns found from {clean_sum_cols}. Available columns: {df.columns.tolist()}")
        return None, {}

    log.append(f"Summary Info: Processing '{index_col}' against numeric columns: {valid_sum_cols}")

    for c in valid_sum_cols:
        df[c] = (
            df[c]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace("$", "", regex=False)
            .str.strip()
            .replace({"": "0", "-": "0", "N/A": "0", "n/a": "0", "nan": "0", "None": "0"})
        )
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0.0)

    header_lookup = {h.strip().lower(): h for h in group_headers}
    section_lookup = {s.strip().lower() for s in section_groups}
    roll_lookup = {r.strip().lower() for r in roll_groups}

    combine_lookup: dict[str, str] = {}
    for output_name, input_headers in combine_groups.items():
        for header in input_headers:
            combine_lookup[header.strip().lower()] = output_name

    raw_results: dict[str, float] = {}
    current_section: str | None = None
    processed_count = 0

    for _, row in df.iterrows():
        label = row.get(index_col)
        if pd.isna(label) or str(label).strip() == "" or str(label).strip().lower() == "nan":
            current_section = None
            continue

        label_str = str(label).strip()
        label_lower = label_str.lower()
        num_val = sum(float(row[c]) for c in valid_sum_cols if pd.notna(row[c]))
        processed_count += 1

        if label_lower in header_lookup:
            canonical = header_lookup[label_lower]
            canon_lower = canonical.lower()

            if canon_lower in section_lookup:
                current_section = canonical
                raw_results.setdefault(canonical, 0.0)
                if canon_lower in roll_lookup:
                    raw_results.setdefault(f"{canonical} (Rollover)", 0.0)
                continue

            current_section = None
            if canon_lower in combine_lookup:
                out_name = combine_lookup[canon_lower]
                raw_results[out_name] = raw_results.get(out_name, 0.0) + num_val
            else:
                raw_results[canonical] = raw_results.get(canonical, 0.0) + num_val
            continue

        if current_section is not None:
            sec_lower = current_section.lower()
            if sec_lower in roll_lookup and "roll" in label_lower:
                roll_key = f"{current_section} (Rollover)"
                raw_results[roll_key] = raw_results.get(roll_key, 0.0) + num_val
            else:
                raw_results[current_section] = raw_results.get(current_section, 0.0) + num_val

    log.append(f"Summary Info: Filtered and aggregated {processed_count} valid rows.")

    consumed = {header.strip().lower() for headers in combine_groups.values() for header in headers}
    results = {k: v for k, v in raw_results.items() if k.lower() not in consumed}

    actual_sheet_name = unique_sheet_title(target_workbook, sheet_name, "Summary")
    ws = target_workbook.create_sheet(title=actual_sheet_name)

    bold_font = Font(name="Calibri", bold=True, size=11)
    header_fill = PatternFill(start_color="D9E1F2", end_color="D9E1F2", fill_type="solid")
    center = Alignment(horizontal="center")

    for col_idx, heading in enumerate(["Description", "Total Plan Activity per FS"], start=1):
        cell = ws.cell(row=1, column=col_idx, value=heading)
        cell.font = bold_font
        cell.fill = header_fill
        cell.alignment = center

    ws.column_dimensions["A"].width = 30
    ws.column_dimensions["B"].width = 18

    for row_num, (group_name, total) in enumerate(results.items(), start=2):
        ws.cell(row=row_num, column=1, value=group_name)
        total_cell = ws.cell(row=row_num, column=2, value=round(total, 2))
        total_cell.number_format = "#,##0.00"

    return actual_sheet_name, results


def build_trial_balance(payload: dict[str, Any]) -> dict[str, Any]:
    log: list[str] = []
    template_path = payload.get("template_path")
    output_path = payload.get("output_path")
    reporting_date = payload.get("reporting_date", "")
    rows = payload.get("rows", [])

    if not template_path or not Path(template_path).exists():
        return {"success": False, "message": "Template workbook not found.", "log": log}

    if not output_path:
        return {"success": False, "message": "No output path provided.", "log": log}

    try:
        template_wb = load_workbook(template_path)
    except Exception as exc:
        return {"success": False, "message": f"Unable to open template: {exc}", "log": log}

    if reporting_date and "1. Procedures" in template_wb.sheetnames:
        template_wb["1. Procedures"]["A2"] = reporting_date

    copied_sheets: list[dict[str, Any]] = []
    summaries: list[dict[str, Any]] = []

    for row in rows:
        validated_path = row.get("validated_path")
        target_sheet_name = row.get("target_sheet_name")
        row_id = row.get("row_id")

        if not validated_path or not target_sheet_name:
            log.append(f"Skipped row {row_id}: missing validated_path or target_sheet_name.")
            continue

        if not Path(validated_path).exists():
            log.append(f"Skipped row {row_id}: validated file not found at {validated_path}.")
            continue

        source_sheet_name, actual_target_sheet_name, error = copy_xlsx_to_sheet(
            validated_path,
            template_wb,
            target_sheet_name,
        )
        if error:
            log.append(f"Row {row_id}: {error}")
            continue

        log.append(f"Row {row_id}: copied '{source_sheet_name}' -> '{actual_target_sheet_name}'.")
        copied_sheets.append(
            {
                "rowId": row_id,
                "sourceSheetName": source_sheet_name,
                "targetSheetName": actual_target_sheet_name,
            }
        )

        if not row.get("use_for_summary"):
            continue

        summary_cfg = row.get("summary_config") or {}
        if not summary_cfg:
            log.append(f"Row {row_id}: summary selected but no summary configuration was provided.")
            continue

        try:
            summary_df = read_validated_df(validated_path, source_sheet_name)
            actual_summary_sheet_name, summary_totals = summarize_hierarchical_df(
                df=summary_df,
                index_col=row.get("index_col", ""),
                sum_cols=row.get("sum_cols", []),
                group_headers=summary_cfg.get("group_headers", []),
                section_groups=summary_cfg.get("section_groups", []),
                roll_groups=summary_cfg.get("roll_groups", []),
                combine_groups=summary_cfg.get("combine_groups", {}),
                target_workbook=template_wb,
                sheet_name=summary_cfg.get("sheet_name", f"{row_id} Summary"),
                log=log,
            )
            if actual_summary_sheet_name:
                summaries.append(
                    {
                        "rowId": row_id,
                        "sourceSheetName": source_sheet_name,
                        "summarySheetName": actual_summary_sheet_name,
                        "totals": summary_totals,
                    }
                )
                log.append(f"Summary sheet '{actual_summary_sheet_name}' written for row {row_id}.")
        except Exception as exc:
            log.append(f"Row {row_id}: summary generation failed: {exc}")

    try:
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        template_wb.save(output_path)
    except Exception as exc:
        return {"success": False, "message": f"Unable to save output: {exc}", "log": log}

    single_summary = summaries[0]["totals"] if len(summaries) == 1 else None

    return {
        "success": True,
        "outputPath": str(Path(output_path).resolve()),
        "copiedSheets": copied_sheets,
        "summaries": summaries,
        "summary": single_summary,
        "log": log,
    }


def main() -> None:
    try:
        payload = json.load(sys.stdin)
        result = build_trial_balance(payload)
        print(json.dumps(result))
        sys.exit(0 if result.get("success") else 1)
    except Exception as exc:
        print(json.dumps({"success": False, "message": str(exc), "log": []}))
        sys.exit(1)


if __name__ == "__main__":
    main()
